### ISSUE TITLE
Wireless PS3 Controller No Longer Working

### ISSUE THREAD

**Issue by MattWatt** [RetroPie/mame4all-pi#1]
I had issues with Mame4All picking up input from my wireless PS3 controller since installing a fresh copy of the new 3.0 final.  What I did discover was that copying the mame binary from my 2.6 image fixed the problem and the controller worked fine.  Something in the code broke wireless functionality for the controller.

**Comment by MattWatt** [comment]
I commented out the last change to minimal.cpp, that re-added the check for controller axis, and recompiled and that solved the problem.  I'm not sure why it was re-added, but there's still a conflict with PS3 wireless controllers.

**Comment by joolswills** [comment]
This should be ok now as the code was removed again last year. closing.
