### ISSUE TITLE
Please help: how to move image to top of 16x9 when rol and forced to 4x3 aspect ratio

### ISSUE THREAD

**Issue by jhudson8** [RetroPie/mame4all-pi#11]
Hello,

I've got a 16x9 TV that I'd like to use for an arcade cabinet placed vertically so only the top 4x3 portion (after rotation) will be visible.

I found out how to rotate the image and force a 4x3 aspect ratio using the following settings in `/opt/retropie/configs/mame-mame4all/mame.cfg`
```
rol=yes
vector_width=640
vector_height=480
```

This works but causes the viewable screen are to be in the middle (horizontally) as seen below
```
_________________
|XXXXXXXXXXXXXXX|
|XXXXXXXXXXXXXXX|
|               |
|               |
|               |
|               |
|               |
|XXXXXXXXXXXXXXX|
|XXXXXXXXXXXXXXX|
```

Can you please tell me what setting I can use to move the viewable image to the top as seen below?
```
_________________
|               |
|               |
|               |
|               |
|               |
|XXXXXXXXXXXXXXX|
|XXXXXXXXXXXXXXX|
|XXXXXXXXXXXXXXX|
|XXXXXXXXXXXXXXX|
```

Thanks very much in advance.

**Comment by joolswills** [comment]
Not possible with this emulator  - please use the retropie forum for more help. I also recommend you use a more up to date emulator for more control like this - eg lr-mame2003 with retropie.
