### ISSUE TITLE
Cannot start mame4all on Retropie 4.6

### ISSUE THREAD

**Issue by ltpitt** [RetroPie/mame4all-pi#18]
Hi all,

I start mame4all on Retropie 4.6, all I get is this image:
https://photos.app.goo.gl/igmjZuminwhJNwE1A

Same identical Raspberry and romset work fine on Retropie 4.5.

Other users have the same problem:
https://retropie.org.uk/forum/topic/25847/imame4all-lr-gpsp-don-t-work-on-retropie-4-6
https://retropie.org.uk/forum/topic/27401/mame4all-not-working-in-rpi-zero-image

Can you please help or point me in the right direction for troubleshooting?

Thanks for your time and patience.

**Comment by ghost** [comment]
will be fixed once https://github.com/RetroPie/mame4all-pi/pull/19  is pulled

**Comment by ltpitt** [comment]
> will be fixed once #19 is pulled

This is the best Xmas gift ever!
