### ISSUE TITLE
Support for Buster / arm64

### ISSUE THREAD

**Issue by rayrayrayraydog** [RetroPie/mame4all-pi#20]
I've managed to compile this on Buster on a Pi3 and spent a lot of time playing with packages/libraries but can't get the emulator to start.  I always get to this error when trying to load a game: 
* failed to add service - already in use?

It's the same on a Pi3 running Buster and a Pi Zero 2 running on arm64 w/ armhf arch support installed.

Is there any plan to create official builds for Buster or Buster/arm64?

**Comment by cmitu** [comment]
The emulator uses specifically the old/proprietary Broadcom GL/video drivers and the Dispmanx API. Both technologies are considered legacy starting with the _bullseye_ release of RaspiOS and they're not included anymore - `mame4all-rpi` will not work out-of-the-box on the new OS (regardless of the Pi model used). As you noticed, you can't even compile it on the new RaspiOS release.

I suggest you use a libretro based core like Mame2003-plus or FinalBurn Neo.

**Comment by rayrayrayraydog** [comment]
@cmitu Thanks for following up.  If anyone is digging into the rabbit hole to find a replacement for this emulator (other than full-on Retroarch) I would suggest advancemame: https://github.com/amadvance/advancemame  I'm getting good performance in very old games like Berzerk and Mario Bros. on a Pi 2 Zero W / arm64 Bullseye using it.
